### ISSUE TITLE
What constitutes an "SDO"?

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/procedures#2]
The registration procedures distinguish between "standards tree" and "vendor/personal tree" for registration, with "standards tree" being reserved for SDOs.

A fairly liberal interpretation of "SDO" has been used - so that, for instance, well known open source projects qualify.
If we keep the distinction, we should perhaps clarify the intent of the term.

**Comment by alvestrand** [comment]
Quoting Mark Nottingham, sent to the mailing list on Feb 1, 2023:

> In London, we talked about potential revisions to the registration procedures.[1] One idea that seemed to have broad support in the room was opening up the standards tree to Open Source projects.
> 
> Upon reflection, I don't think that's a great path forward. 
> 
> An OS project is an implementation, and so it fits more naturally in the vendor tree -- just as with proprietary software, interoperability is defined by the instance of the software, not a specification that can be freely implemented by others. Sure, one might be able to dig through the codebase, or the project might generously document its format and make it open, but the former is onerous and is no great assurance of interior, while the latter is optional, not tied to the nature of Open Source (and indeed many projects don't document their formats well).
> 
> What I'm interested in getting registered are community-created formats that are _not_ specific to any implementation (although they may start with one, of course); they might use Open Source infrastructure (such as GitHub, GitLab, etc.), but they're of a different nature, because they're intended for interoperability. They just lack the formal recognition as a SDO.
> 
> We could ask the IESG to be more generous in recognising SDOs, but that's onerous enough to burden folks in the IETF and discourage folks on the 'outside'.
> 
> Instead, I'd suggest giving the Media Types Reviewer(s) the discretion to allow registration into the standards tree on a case-by-case basis, using the following as guides:
>  - whether or not there is a well-defined specification for the format
>  - whether or not that specification is free from being tied to or heavily associated with one implementation
>  - whether or not there are multiple interoperable implementations of the format
>  - whether or not the specification is freely available at a stable location
>  - whether or not the requested name is appropriate to the use case, and not so generic that it may be considered 'squatting'
>  - whether or not there is a potential or actual conflict with IETF work or work at other recognised SDOs (present or future)
>  - whether or not there is evidence of broad adoption (with 'broad' being interpreted liberally)
> 
> Not all of these questions need to be answered in the affirmative.
>

**Comment by gklyne** [comment]
Mark's message mentioned above, and ensuing thread, at:

https://mailarchive.ietf.org/arch/msg/media-types/subyRUPbfwvq2Hz2XyhiBaskfV4/

**Comment by alvestrand** [comment]
This issue is addressed by draft-ietf-mediaman-standards-tree, and will be closed once that document is approved.

**Comment by alvestrand** [comment]
draft-ietf-mediaman-standards-tree represents WG consensus on the issue, and will be incorporated in 6838bis.
Closing this issue.
